V7 docs
CCALI/A2JDAT pull request #41
Opened 2021-02-15 21:29 UTC by tobiasnteireho

update documentation for DAT. Addresses calibration, azure upgrade issues, and nvm upgrade issues

fix #37 
fix #13 
fix #7

2021-02-15 22:10 UTC, mikemitchel requested changes
looks good, just found the one typo

2021-02-15 22:10 UTC, mikemitchel commented on README.md
>  WKHTMLTOPDF_DPI- desired default dpi to render pdfs. CALI reccomends minimum of 300
recommends

2021-02-15 22:30 UTC, JessicaFrank commented on README.md
> +**The folder structure has changed.** It is recommended that your current setup is backed up. This means at a minimum, config.json and ecosystem.config.js. Alternatively you may checkout/unzip this r
double space after the word "into"

2021-02-15 22:30 UTC, JessicaFrank commented on README.md
> +*The folder structure has changed.* It is recommended that your current setup is backed up. This means at a minimum, config.json and ecosystem.config.js. Alternatively you may checkout/unzip this rep
double space after word "into"

2021-02-16 00:19 UTC, tobiasnteireho commented on README.md
>  WKHTMLTOPDF_DPI- desired default dpi to render pdfs. CALI reccomends minimum of 300
fixed in latest commit

2021-02-16 00:19 UTC, tobiasnteireho commented on README.md
> +**The folder structure has changed.** It is recommended that your current setup is backed up. This means at a minimum, config.json and ecosystem.config.js. Alternatively you may checkout/unzip this r
fixed in latest commit

2021-02-16 14:12 UTC, mikemitchel approved these changes
👍

2021-02-16 19:35 UTC, merged